version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_fleet
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fleet_management
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
